# Generated by Django 5.2.9 on 2025-12-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='voluntarios',
        ),
        migrations.RemoveField(
            model_name='voluntario',
            name='fecha_registro',
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='telefono',
            field=models.CharField(default='sin-telefono', max_length=20),
            preserve_default=False,
        ),
    ]
