# Generated by Django 5.2.9 on 2025-12-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0002_remove_evento_voluntarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='voluntarios',
            field=models.ManyToManyField(blank=True, to='voluntarios.voluntario'),
        ),
    ]
